const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
let history=JSON.parse(localStorage.getItem("seg_history")||"[]");
function showView(id){$$(".view").forEach(v=>v.classList.remove("active"));$("#"+id).classList.add("active");const titles={dashboard:"Visão geral",new:"Nova análise",history:"Histórico",results:"Resultados"};$("#pageTitle").textContent=titles[id]||"Visão geral";$$(".nav").forEach(n=>n.classList.toggle("active",n.dataset.view===id));if(id==="history")renderHistory()}
$$(".nav").forEach(n=>n.onclick=()=>showView(n.dataset.view));$("#menu").onclick=()=>$(".sidebar").classList.toggle("open");
function clean(v){return v.trim().replace(/^@/,"").replace(/[^a-zA-Z0-9._]/g,"").slice(0,30)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
$("#start").onclick=async()=>{const u=clean($("#username").value);$("#error").textContent="";if(!u){$("#error").textContent="Informe um nome de usuário.";return}const btn=$("#start");btn.disabled=true;btn.textContent="Processando…";await new Promise(r=>setTimeout(r,900));const now=new Date().toLocaleString("pt-BR");history.unshift({username:u,created:now});history=history.slice(0,50);localStorage.setItem("seg_history",JSON.stringify(history));renderResult(u);btn.disabled=false;btn.textContent="Iniciar análise"};
function renderResult(u){$("#resultTitle").textContent="@"+u;$("#resultMeta").textContent="Consulta iniciada em "+new Date().toLocaleString("pt-BR");$("#resultsBody").innerHTML='<tr><td><b>@'+escapeHtml(u)+'</b></td><td>Dados públicos</td><td>Disponibilidade depende da fonte conectada.</td><td>—</td></tr>';$("#resultCount").textContent="1";$("#siteCount").textContent="0";showView("results")}
function renderHistory(){const el=$("#historyList");if(!history.length){el.className="empty";el.textContent="Nenhuma análise realizada ainda.";return}el.className="";el.innerHTML=history.map(x=>'<div style="display:flex;justify-content:space-between;padding:14px 0;border-bottom:1px solid #eee"><span><b>@'+escapeHtml(x.username)+'</b><small style="display:block;color:#888">'+escapeHtml(x.created)+'</small></span><button class="secondary" onclick="renderResult(\''+escapeHtml(x.username)+'\')">Abrir</button></div>').join("")}
$("#export").onclick=()=>{const u=$("#resultTitle").textContent;const rows=[["Perfil","Nome","Biografia","Site público"],[u,"Dados públicos","Disponibilidade depende da fonte conectada.",""]];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="analise-instagram.csv";a.click();URL.revokeObjectURL(a.href);localStorage.setItem("seg_exports",String(Number(localStorage.getItem("seg_exports")||0)+1));};
$("#statAnalyses").textContent=history.length;$("#statProfiles").textContent=history.length;$("#statExports").textContent=localStorage.getItem("seg_exports")||"0";